from typing import Protocol, TypeVar, Optional
from uuid import UUID

T = TypeVar("T")


class BaseRepository(Protocol[T]):
    async def get_by_id(self, entity_id: UUID) -> Optional[T]: ...
    async def save(self, entity: T) -> T: ...
    async def get_all(self, limit: int = 50, offset: int = 0) -> list[T]: ...
    async def delete(self, entity: T) -> None: ...