from typing import Protocol, TypeVar
from uuid import UUID

T = TypeVar("T")


class BaseRepository(Protocol[T]):
    async def get_by_id(self, entity_id: UUID) -> T | None: ...
    async def save(self, entity: T) -> T: ...
    async def get_all(self, limit: int = 50, offset: int = 0) -> list[T]: ...
    async def delete(self, entity_id: UUID) -> bool: ...
    async def exists(self, entity_id: UUID) -> bool: ...