from uuid import UUID

from app.domain.entities.snapshot.models import Snapshot
from app.domain.entities.snapshot_file.models import SnapshotFile
from app.domain.repositories.base import BaseRepository
from app.domain.entities.snapshot.models import SnapshotStatus


class SnapshotRepository(BaseRepository[Snapshot]):
    async def get_by_status_by_root_id(self, status: SnapshotStatus, root_id: UUID) -> list[Snapshot]: ...
    async def get_all_by_root_id(self, root_id: UUID) -> list[Snapshot]: ...
    async def get_latest_completed_by_root_id(self, root_id: UUID) -> Snapshot | None: ...
    async def get_previous_completed_by_root_id(self, root_id: UUID) -> Snapshot | None: ...

    async def save_snapshot_files(self, files: list[SnapshotFile]): ...
    async def get_all_snapshot_files_by_snapshot_id(self, snapshot_id: UUID) -> list[SnapshotFile]: ...
    async def get_files_count_by_snapshot_id(self, snapshot_id: UUID) -> int: ...
